[package]
name = "block_get"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iota-sdk = { git = "https://github.com/iotaledger/iota-sdk", branch = "develop" }
tokio = { version = "1.12.0", features = ["full"] }
prefix-hex = { version = "0.7.1", default-features = false, features = [
    "primitive-types",
] }
